FROM ghcr.io/ggml-org/llama.cpp:server

ENV LLAMA_CHAT_TEMPLATE_KWARGS='{"reasoning_effort":"low","builtin_tools":["python"]}'
ENV LLAMA_ARG_HF_REPO=ggml-org/gpt-oss-20b-GGUF
ENV LLAMA_ARG_API_PREFIX=$LLAMA_ARG_API_PREFIX
ENV LLAMA_ARG_CTX_SIZE=0
ENV LLAMA_ARG_CONTEXT_SHIFT=1
ENV LLAMA_ARG_NO_WEBUI=1
ENV LLAMA_ARG_JINJA=1

EXPOSE 8080/tcp

HEALTHCHECK CMD curl -f http://[::]:8080/$LLAMA_ARG_API_PREFIX/health
ENTRYPOINT [ "./llama-server" ]
